language: python
python:
  - 3.9
install:
  - pip install -q pipenv codecov
  - pipenv sync --dev
script:
  - pipenv run flake8
  - pipenv run pytest libpythonpro --cov=libpythonpro
after_success:
  - pipenv run codecov
